/*
  Jaime Margolin A01019332
  Juan carlos Leon A01020200
  Rodrigo Solana A01129839
*/

namespace Int64 {

    enum TokenCategory {
      BREAK,
      ELSE,
      RETURN,
      CASE,
      FALSE,
      SWITCH,
      CONTINUE,
      FOR,
      TRUE,
      DEFAULT,
      IF,
      DO,
      IN,
      VAR,
      WHILE,
      ASSIGN,
      QUESTION_MARK,
      EQUAL,
      NOT_EQUAL,
      GREATER_THAN,
      GREATER_OR_EQUAL_THAN,
      LESS_THAN,
      LESS_OR_EQUAL_THAN,
      OR,
      BIT_OR,
      XOR,
      AND,
      BIT_AND,
      SHIFT_LEFT,
      SHIFT_RIGHT,
      SHIFT_RIGHT_ALT,
      POWER,
      MULTIPLICATION,
      SUBTRACTION,
      ADDITION,
      DIVISION,
      MODULUS,
      NOT,
      BIT_NOT,
      BASE_2,
      BASE_8,
      BASE_16,
      BASE_10,
      PARENTHESIS_LEFT,
      PARENTHESIS_RIGHT,
      CURLY_BRACE_LEFT,
      CURLY_BRACE_RIGHT,
      COLON,
      SEMICOLON,
      COMMA,
      STRING,
      CHARACTER,
      WHITE_SPACE,
      UNKNOWN,
      IDENTIFIER,
      EOF
    }
}
